### ISSUE TITLE
current client will not connect

### ISSUE THREAD

**Issue by parakeet-live** [Airkek/Chikatto#3]
so i'm using the latest client, with chikatto running on win11.
i'm using ngrok to provide me with SSL but the client is just giving me a connection failed. any help?

**Comment by Airkek** [comment]
i'm using nginx for ssl certificate and *.chikatto.dev reverse proxied to localhost:5000
all works

**Comment by Airkek** [comment]
i never used ngrok so can you give me more info?

**Comment by parakeet-live** [comment]
wait, this might be on me. if you have to have it reverse proxied through any sub-domain that osu! specifies it might be me. I just booted ngrok and threw a dev server flag. Although, I've never used nginx, and apache isn't helping me with reverse proxying. You mind helping me out though?

**Comment by Airkek** [comment]
> You mind helping me out though?

Sure, DM me 
Keijia#\0161

**Comment by parakeet-live** [comment]
*hidden*

**Comment by parakeet-live** [comment]
![image](https://user-images.githubusercontent.com/79934414/142775061-98a3f4de-7d13-4737-9647-71d2b25dc4e6.png)
new issue when logging in
