### ISSUE TITLE
Не работает SSL подключение

### ISSUE THREAD

**Issue by owoPeef** [Airkek/Chikatto#5]
Сервер запускается, но не работает с SSL и https

**Comment by Airkek** [comment]
> Сервер запускается, но не работает с SSL и https

для этого тебе надо использовать nginx (или apache)

**Comment by owoPeef** [comment]
Это понятно, но в интернете не найти как для этого именно использовать

**Comment by Airkek** [comment]
> Это понятно, но в интернете не найти как для этого именно использовать

тебе надо просто настроить reverse proxy на домены 
a.domanin
c.domain
osu.domain
(еще какие-то вроде, честно не помню, для осу директа)

с портами 80 и 443 и добавить SSL_CERTIFICATE.
Можно воспользоваться инструкцией для gulag, она мало чем отличается https://github.com/osuAkatsuki/bancho.py

**Comment by owoPeef** [comment]
А запускать сервер надо под адресом localhost? Или как

**Comment by Airkek** [comment]
> А запускать сервер надо под адресом localhost? Или как

да, в nginx 
proxy_pass http://localhost:port
